name: ItemName
main: PTK\main
api: [2.0.0, 3.0.0 ,3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3]
version: 0.2german
author: PTK-KienPham
commands:
 trash:
  description: Đổi tên vật phẩm!
  permission: trash
permissions:
  trash:
    description: Zugriff auf alle Kommandos
    default: true